version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
      - ./reservasi/reservasi.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: buayakecil
      MYSQL_DATABASE: reservasi
      MYSQL_USER: userawan
      MYSQL_PASSWORD: buayakecil

  worker:
    build:
      context: ./
    depends_on:
      - db
    expose:
      - "5000"
    environment:
      DB_HOST: db
      DB_NAME: reservasi
      DB_USER: wordpress
      DB_PASSWORD: wordpress

  load-balance:
    depends_on:
      - worker
    image: nginx
    ports:
      - "8000:80"
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  dbdata: